### ISSUE TITLE
Add an @href attribute to <opening>

### ISSUE THREAD

**Issue by kerstarno** [ArchivesPortalEuropeFoundation/EAG2012#2]
_Provide a general summary of the issue in the Title above._

## Creator of issue
_State your name, organisation and ways to reach you._
Name: Jane Stevenson
Organisation: Archives Hub
Email: jane.stevenson@jisc.ac.uk
GitHub username (if applicable): janestevenson

## The issue relates to
_Replace the ' ' (space) inside the brackets with an 'x' to mark your choice._
- [x] Schema issue
- [ ] Conversion issue
- [x] Documentation issue
- [x] Other

## Context
_Tell us what should happen and how things should work. If reporting a bug, tell us what happens instead of the expected behaviour including a description of steps to reproduce the issue. If suggesting a change/improvement, explain the difference from current behaviour._
_Tell us how this issue affects you and what you are trying to accomplish, i.e. why this needs to be changed._
_Write your text after the "Text:" below._
* Allow the attribute @href for /repository/timetable/opening, which will enable Institution Managers to use a link to information on the opening hours of their institution on their own websites. The implementation can be done just like the one for: /repository/services/searchroom/readersTicket or /repository/services/searchroom/advancedOrders.
* Add another text field with as label "Opening hours link:" in the section of the opening hours, so between the horizontal blue lines of this section, but right under the button which now has as text "Add opening times"
* Change the text of the above mentioned button from "Add opening times" into: "Add extra (line for) opening hours text"
* Change the text of the label of the first text field of the current section of the opening hours from "Opening hours*:" into "Opening hours text*:"
In this way, Institution Managers can still choose to stick to text only or to use a weblink, for which they still will need to fill in the first text field, for instance saying: "See our opening hours over here", after which they have to fill in the url for the link in the new "Opening hours link:" field.
* Requires according change in the EAG2012 schema and in the display of institution information.

## Name and place of the specific element / attribute, that needs to be changed / added
_Name the element or attribute that you would want to change or add._
Element: /repository/timetable/opening
Attribute:

## Name(s) of (all) parent elements where a new element should be added to the schema or conversion
_List all parent elements to which a new element should be added in the schema or conversion. Add more lines for "Parent element(s)", if needed._
Parent element 1:
Parent element 2:
Parent element 3:
Parent element 4:
Parent element 5:

## Name(s) of (all) sub-elements the new / changed element should have
_List all sub-elements that should be allowed within the new element in the schema or conversion. Add more lines for "Sub-element(s)", if needed._
Sub-element 1:
Sub-element 2:
Sub-element 3:
Sub-element 4:
Sub-element 5:

## Attributes that should be used with the new / changed element
_List all attributes that should be available with the new element. Provide suggestions for specific default values (if applicable)._
Attribute 1 (with default values): `@href`
Attribute 2 (with default values):
Attribute 3 (with default values):
Attribute 4 (with default values):
Attribute 5 (with default values):

## Example for usage of the new / changed element (including potential attributes) in the portal (use case)
_Describe how the new / changed element should be used in the Archives Portal Europe, e.g. in terms of display._
_Write your text after the "Text:" below._
* Text: See description of the issue above

## Example of XML code
_Provide a sample encoding in XML of the new / changed element (with potential attributes)._
_In case of a conversion issue, the XML should ideally show the way an issue is dealt with now and the way you would like it to be dealt with in the future._
_Write your text after the "Example:" below._
* Example:
`<opening href="http://www.link.eu">`See our opening hours here.`<opening>`

**Comment by kerstarno** [comment]
This is being dealt with in the Jira issue ASUP-99.

**Comment by SJagodzinski** [comment]
I agree, no objections from me.

**Comment by kerstarno** [comment]
This change has been implemented in EAG2012 with the release 2.7 of Archives Portal Europe in September 2019. 

For Archives Portal Europe, the change also included updates to the EAG forms in the Dashboard and in the Data Preparation Tool as well as the display in the Portal.
