### ISSUE TITLE
Review the use of the various name elements in EAG2012

### ISSUE THREAD

**Issue by kerstarno** [ArchivesPortalEuropeFoundation/EAG2012#3]
_Provide a general summary of the issue in the Title above._

## Creator of issue
_State your name, organisation and ways to reach you._
Name: Jane Stevenson
Organisation: Archives Hub
Email: jane.stevenson@jisc.ac.uk
GitHub username (if applicable): janestevenson

## The issue relates to
_Replace the ' ' (space) inside the brackets with an 'x' to mark your choice._
- [x] Schema issue
- [ ] Conversion issue
- [x] Documentation issue
- [x] Other

## Context
_Tell us what should happen and how things should work. If reporting a bug, tell us what happens instead of the expected behaviour including a description of steps to reproduce the issue. If suggesting a change/improvement, explain the difference from current behaviour._
_Tell us how this issue affects you and what you are trying to accomplish, i.e. why this needs to be changed._
_Write your text after the "Text:" below._
* There are three different elements in EAG2012 at the moment to encode variations of the name of an institution. While `<autform>` might be relatively self-explaining, there is certain overlap between `<parform>` and `<nonpreform>`, which makes the distinction between them not always easy. 
* There has been some work done on the labels used in the EAG form of the dashboard, but it would be worth to review this question more generally. However, that might only be relevant in the context of a more general revision of EAG.

## Name and place of the specific element / attribute, that needs to be changed / added
_Name the element or attribute that you would want to change or add._
Element: `<autform>`, `<parform>`,  `<nonpreform>`
Attribute:

## Name(s) of (all) parent elements where a new element should be added to the schema or conversion
_List all parent elements to which a new element should be added in the schema or conversion. Add more lines for "Parent element(s)", if needed._
Parent element 1:
Parent element 2:
Parent element 3:
Parent element 4:
Parent element 5:

## Name(s) of (all) sub-elements the new / changed element should have
_List all sub-elements that should be allowed within the new element in the schema or conversion. Add more lines for "Sub-element(s)", if needed._
Sub-element 1:
Sub-element 2:
Sub-element 3:
Sub-element 4:
Sub-element 5:

## Attributes that should be used with the new / changed element
_List all attributes that should be available with the new element. Provide suggestions for specific default values (if applicable)._
Attribute 1 (with default values):
Attribute 2 (with default values):
Attribute 3 (with default values):
Attribute 4 (with default values):
Attribute 5 (with default values):

## Example for usage of the new / changed element (including potential attributes) in the portal (use case)
_Describe how the new / changed element should be used in the Archives Portal Europe, e.g. in terms of display._
_Write your text after the "Text:" below._
* Text:

## Example of XML code
_Provide a sample encoding in XML of the new / changed element (with potential attributes)._
_In case of a conversion issue, the XML should ideally show the way an issue is dealt with now and the way you would like it to be dealt with in the future._
_Write your text after the "Example:" below._
* Example:

**Comment by SJagodzinski** [comment]
EAC-CPF team in TS-EAS is going to discuss a similiar question during the f2f meeting in Aguust 2019. 

Any changes in EAG might be aligned with EAC-CPF revision. Let's move this discussion to autumn.

**Comment by kerstarno** [comment]
Sounds reasonable. Agreed with the suggestion to await results from the discussion within TS-EAS.

**Comment by SJagodzinski** [comment]
During the TS-EAS f2f in August 2019 the name issue for EAC-CPF wasn't finally solved. 
Details will be discussed during the next weeks.

The status of a name, auhorised or alternative, is suggested to be encoded with a new attribute `@status`. Other name encoding questions are still pending and might only solved during the next f2f meeting in March 2020.

**Comment by 50119572L** [comment]
Then, Do you prefer wating to the  TS-EAS? 
I guess, we can move this issue to our next face to face meeting, and there, Kerstin and Silke tell us the details of the discusion and how is the situation, and then deciding if we continue waiting or not.

**Comment by kerstarno** [comment]
At their meeting on 6 September 2019, the Working Group on Standards agreed to put this issue on hold to see how the conversation on names in EAC-CPF evolves.

**Comment by kerstarno** [comment]
During their meeting on 27 November 2019, the Working Group on Standards (WGoS) agreed the following step-by-step approach:

- Ensure consistent use of labels in all user interfaces, forms and documents of the Archives Portal Europe; this means the labels currently used in the portal will also be used in the dashboard and DPT forms: 
  - `<autform>` will be kept as is, i.e. "Name of the institution"
  - `<parform>` will be labelled as "Name of the archive (in other languages)"; forms in the dashboard and DPT as well as the EAG Tag Library will be updated accordingly
  - `<nonpreform>` will be labelled as "Alternative/previous name(s) of the archive"
- Follow up on the change of labels for `<parform>` and `<nonpreform>` with accordingly updated descriptions in the EAG Tag Library
  - It has been noted that the change for `<parform>` means that this element will be used in a more restrictive way. WGoS has agreed to evaluate the impact of this change as part of the overall analysis, which is planned on the EAG corpus of Archives Portal Europe.
- Make `<useDates>` an optional sub-element of `<nonpreform>` as a result of the change in scope as mentioned above. 
- Await final decisions on names in EAC-CPF for any further changes.

**Comment by kerstarno** [comment]
Interim note: 

The properties file [eag2012](https://github.com/ArchivesPortalEuropeFoundation/ape-dpt/blob/master/DPTutils/src/main/resources/i18n/eag2012.properties) has been updated (rows 58, 197, 199, 239, 240, and 241). Will need to be followed through with other language properties.

**Comment by kerstarno** [comment]
The EAG 2012 schema has been updated accordingly on [GitHub](https://github.com/ArchivesPortalEuropeFoundation/ape-dpt/blob/master/DPTutils/src/main/resources/eag_2012.xsd) in the master and current development branches and will become available at http://www.archivesportaleurope.net/Portal/profiles/eag_2012.xsd with the next release to PROD.

**Comment by kerstarno** [comment]
The schema update to `<useDates>` not being required anymore in `<nonpreform>` as well as the update to the properties has been released. 

Follow-up tasks in the context of APE (@stefanpapp-ape)
- Ensure that files without `<useDates>` in `<nonpreform>` will validate on upload and will be processed (as minor revision task)
- Update the EAG forms (in dashboard and DPT) to not require "Years when this name was used" anymore (as part of the potential changes to the display for the major revision)

See Jira issues STANDARDS-74 and -77.

**Comment by kerstarno** [comment]
This will be followed up in the context of the major revision, where `<autform>`, `<parform>` and `<nonpreform>` will be replaced by `<nameEntry>` (see #88, #89, #90, and #91).
