### ISSUE TITLE
Add @href attribute to <restaccess>

### ISSUE THREAD

**Issue by janestevenson** [ArchivesPortalEuropeFoundation/EAG2012#38]
_Provide a general summary of the issue in the Title above._

## Creator of issue
_State your name, organisation and ways to reach you._
Name: Jane Stevenson
Organisation: Archives Hub
Email: jane.stevenson@jisc.ac.uk
GitHub username (if applicable): @janestevenson

## The issue relates to
_Replace the ' ' (space) inside the brackets with an 'x' to mark your choice._
- [X] Schema issue
- [ ] Conversion issue
- [X] Documentation issue
- [X] Other

## Context
_Tell us what should happen and how things should work. If reporting a bug, tell us what happens instead of the expected behaviour including a description of steps to reproduce the issue. If suggesting a change/improvement, explain the difference from current behaviour._
_Tell us how this issue affects you and what you are trying to accomplish, i.e. why this needs to be changed._
_Write your text after the "Text:" below._
* Text: At the moment, it is not possible to add a link to information about access conditions for a repository.  Usually the repository will put access conditions information on their own website, and update the website as needed. It makes sense to be able to link to this information.  It does not make sense to have an @href attribute for `<termsOfUse>` but not for this `<restaccess>` tag.  Surely the principle applies to both tags?  

## Name and place of the specific element / attribute, that needs to be changed / added
_Name the element or attribute that you would want to change or add._
Element: `<restaccess>`
Attribute: href

## Name(s) of (all) parent elements where a new element should be added to the schema or conversion
_List all parent elements to which a new element should be added in the schema or conversion. Add more lines for "Parent element(s)", if needed._
Parent element 1:  
Parent element 2:
Parent element 3:
Parent element 4:
Parent element 5:

## Name(s) of (all) sub-elements the new / changed element should have
_List all sub-elements that should be allowed within the new element in the schema or conversion. Add more lines for "Sub-element(s)", if needed._
Sub-element 1:
Sub-element 2:
Sub-element 3:
Sub-element 4:
Sub-element 5:

## Attributes that should be used with the new / changed element
_List all attributes that should be available with the new element. Provide suggestions for specific default values (if applicable)._
Attribute 1 (with default values):
Attribute 2 (with default values):
Attribute 3 (with default values):
Attribute 4 (with default values):
Attribute 5 (with default values):

## Example for usage of the new / changed element (including potential attributes) in the portal (use case)
_Describe how the new / changed element should be used in the Archives Portal Europe, e.g. in terms of display._
_Write your text after the "Text:" below._
* Text:

## Example of XML code
_Provide a sample encoding in XML of the new / changed element (with potential attributes)._
_In case of a conversion issue, the XML should ideally show the way an issue is dealt with now and the way you would like it to be dealt with in the future._
_Write your text after the "Example:" below._
* Example:
```
<access question="yes">
  <restaccess xml:lang="eng">Readers ticket required.</restaccess>
  <restaccess href="https://www.library.manchester.ac.uk/special-collections/access-the-special-collections/">Further information on access. </restaccess>
</access> 
```

**Comment by kerstarno** [comment]
Just as a note - and not necessarily opposing the suggested change for `<restaccess>`: EAG does include a dedicated element `<readersTicket>`, where `@href` already is available. So, we might want to also look at this element in connection with the example provided here as well as thinking about alternative examples more specifically with regard to access restrictions.

**Comment by janestevenson** [comment]
Agreed by the WGoS, 18/8/20.  Also agreed we need to flag up related tags that give more specific info, e.g. <readersTicket>

**Comment by kerstarno** [comment]
The EAG 2012 schema has been updated accordingly on [GitHub](https://github.com/ArchivesPortalEuropeFoundation/ape-dpt/blob/master/DPTutils/src/main/resources/eag_2012.xsd) in the master and current development branches and will become available at http://www.archivesportaleurope.net/Portal/profiles/eag_2012.xsd with the next release to PROD.

**Comment by kerstarno** [comment]
The updated schema has been published.

Follow-up tasks in the context of APE (@stefanpapp-ape)

- Ensure that files including `@href` with `<restaccess>` will validate on upload and will be processed (as minor revision task)
- Update the EAG forms (in dashboard and DPT) by adding a new field "Access restrictions link" underneath the current "Access restrictions" field with the same functionality as e.g. the "Opening hours link" (including a check that the content provided is a complete URL) in the "Your institution" tab (after having clicked "Add further access information") and in the "Access and services" tab (as part of potential changes to the forms for the major revision)
- Update the EAG forms (in dashboard and DPT) to say "Access restrictions text" instead of "Access restrictions" in the "Your institution" and "Access and services" tabs
- Ensure that the display in the portal picks up on links if provided in the same way as it does e.g. for opening hours (as part of the potential changes to the display for the major revision)

See Jira issue STANDARDS-109.

**Comment by kerstarno** [comment]
The suggestion to add `@href` to `<restaccess>` has already been implemented in the current EAG 2012 schema. All pending changes with regard to documentation, forms used in APE's tools, and display in APE have now become part of the major revision and will be followed through in accordance with #58.
