### ISSUE TITLE
Add cubic metres to the <extent><num> @unit controlled list

### ISSUE THREAD

**Issue by janestevenson** [ArchivesPortalEuropeFoundation/EAG2012#39]
_Provide a general summary of the issue in the Title above._

## Creator of issue
_State your name, organisation and ways to reach you._
Name: Jane Stevenson
Organisation: Jisc
Email: 
GitHub username (if applicable): @janestevenson 

## The issue relates to
_Replace the ' ' (space) inside the brackets with an 'x' to mark your choice._
- [x] Schema issue
- [ ] Conversion issue
- [ ] Documentation issue
- [ ] Other

## Context
_Tell us what should happen and how things should work. If reporting a bug, tell us what happens instead of the expected behaviour including a description of steps to reproduce the issue. If suggesting a change/improvement, explain the difference from current behaviour._
_Tell us how this issue affects you and what you are trying to accomplish, i.e. why this needs to be changed._
_Write your text after the "Text:" below._
* Text:

Currently @unit only allows for squaremetre, linearmetre. These do not give an accurate measurement of space as they are not 3-dimensional. In the UK archivists often use cubic metres, and I would have thought others do the same, as this gives an accurate measurement.  So, simply allow for cubicmetres as a value alongside those already allowed.  It would normally be 'cubic metres' but to be consistent it could be 'cubicmetre'. 

## Name and place of the specific element / attribute, that needs to be changed / added
_Name the element or attribute that you would want to change or add._
Element: <extent><num>
Attribute: @unit

## Name(s) of (all) parent elements where a new element should be added to the schema or conversion
_List all parent elements to which a new element should be added in the schema or conversion. Add more lines for "Parent element(s)", if needed._
Parent element 1:
Parent element 2:
Parent element 3:
Parent element 4:
Parent element 5:

## Name(s) of (all) sub-elements the new / changed element should have
_List all sub-elements that should be allowed within the new element in the schema or conversion. Add more lines for "Sub-element(s)", if needed._
Sub-element 1:
Sub-element 2:
Sub-element 3:
Sub-element 4:
Sub-element 5:

## Attributes that should be used with the new / changed element
_List all attributes that should be available with the new element. Provide suggestions for specific default values (if applicable)._
Attribute 1 (with default values):
Attribute 2 (with default values):
Attribute 3 (with default values):
Attribute 4 (with default values):
Attribute 5 (with default values):

## Example for usage of the new / changed element (including potential attributes) in the portal (use case)
_Describe how the new / changed element should be used in the Archives Portal Europe, e.g. in terms of display._
_Write your text after the "Text:" below._
* Text:

## Example of XML code
_Provide a sample encoding in XML of the new / changed element (with potential attributes)._
_In case of a conversion issue, the XML should ideally show the way an issue is dealt with now and the way you would like it to be dealt with in the future._
_Write your text after the "Example:" below._
* Example:
```
 <repository>
   <holdings>
     <extent>
       <num unit="cubicmetre">120</num>
     </extent>
   </holdings>
 </repository>
```

**Comment by kerstarno** [comment]
Will be on the agenda for the next WGoS meeting on 20 October.

A schema change would apply to the definition of the element `<num>` which can be used in various contexts (`<repositorarea>`, `<lenghtshelf>`, `<workplaces>`, `<computerplaces>`, `<microfilmplaces>`, `<monographicpub>`, `<serialpub>`).
```
    <xs:complexType name="num" mixed="true">
        <xs:attribute name="unit" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="squaremetre"/>
                    <xs:enumeration value="linearmetre"/>
                    <xs:enumeration value="site"/>
                    <xs:enumeration value="book"/>
                    <xs:enumeration value="title"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attributeGroup ref="sourceAttribute"/>
    </xs:complexType>
```

**Comment by kerstarno** [comment]
During their meeting on 20 October 2020, WGoS agreed to add "cubicmetre" as an additional value for the attribute `@unit` for `<num>`. 

Additionally, we discussed adding a value (or several values?) for capturing the extent of digital collections. While there was general inclination to allow for this option, it was decided to do some more research with regard to how this is currently measured (MB, GB, TB, number of files by type, etc.). Examples are to be gathered in this issue here.

**Comment by kerstarno** [comment]
E.g. 

- https://www.archives.gov/research/catalog/lcdrg/elements/extent.html - under "Data files"
- https://francearchives.fr/file/956578222624a218b1c63590d08b31fdbc1ec308/FRAF_2019_RA.pdf - various examples of measurements and statistics throughout the text

**Comment by kerstarno** [comment]
The updated schema has been published.

Follow-up tasks in the context of APE (@stefanpapp-ape)
- Ensure that files including <extent> information with <num unit="cubicmetre"> will validate on upload and will be processed (as minor revision task)
- Update the EAG forms (in dashboard and DPT) to enable a (drop-down) choice between "squaremetre" and "cubicmetre" for "Extent of the archive buildings area (m²):" in the "Description" tab and remove "(m²)" from the label (as part of potential changes to the forms for the major revision)
- Update the EAG forms (in dashboard and DPT) to enable a (drop-down) choice between "linearmetre" and "cubicmetre" for "Extent of the holdings (linear metres):" in the "Description" tab and remove "(linear metres)" from the label (as part of potential changes to the forms for the major revision)

See Jira issue STANDARDS-108.

**Comment by kerstarno** [comment]
The display and documentation change will be handled as part of the major revision (see #137 for details of changes to and conversion of `<holdings>` and its sub-elements). This issue here can hence be closed.
