### ISSUE TITLE
Review elements with longer descriptive texts to allow for line breaks

### ISSUE THREAD

**Issue by kerstarno** [ArchivesPortalEuropeFoundation/EAG2012#5]
_Provide a general summary of the issue in the Title above._

## Creator of issue
_State your name, organisation and ways to reach you._
Name: Jane Stevenson
Organisation: Archives Hub
Email: jane.stevenson@jisc.ac.uk
GitHub username (if applicable): janestevenson

## The issue relates to
_Replace the ' ' (space) inside the brackets with an 'x' to mark your choice._
- [x] Schema issue
- [ ] Conversion issue
- [x] Documentation issue
- [x] Other

## Context
_Tell us what should happen and how things should work. If reporting a bug, tell us what happens instead of the expected behaviour including a description of steps to reproduce the issue. If suggesting a change/improvement, explain the difference from current behaviour._
_Tell us how this issue affects you and what you are trying to accomplish, i.e. why this needs to be changed._
_Write your text after the "Text:" below._
* This suggestion came up in the context of `<opening>`, where it is currently only possible to have the information displayed in various lines, by repeating the element. However, there might be other elements that could benefit from the option to include linebreaks. To be reviewed in the context of a bigger revision of EAG.

## Name and place of the specific element / attribute, that needs to be changed / added
_Name the element or attribute that you would want to change or add._
Element:
Attribute:

## Name(s) of (all) parent elements where a new element should be added to the schema or conversion
_List all parent elements to which a new element should be added in the schema or conversion. Add more lines for "Parent element(s)", if needed._
Parent element 1:
Parent element 2:
Parent element 3:
Parent element 4:
Parent element 5:

## Name(s) of (all) sub-elements the new / changed element should have
_List all sub-elements that should be allowed within the new element in the schema or conversion. Add more lines for "Sub-element(s)", if needed._
Sub-element 1:
Sub-element 2:
Sub-element 3:
Sub-element 4:
Sub-element 5:

## Attributes that should be used with the new / changed element
_List all attributes that should be available with the new element. Provide suggestions for specific default values (if applicable)._
Attribute 1 (with default values):
Attribute 2 (with default values):
Attribute 3 (with default values):
Attribute 4 (with default values):
Attribute 5 (with default values):

## Example for usage of the new / changed element (including potential attributes) in the portal (use case)
_Describe how the new / changed element should be used in the Archives Portal Europe, e.g. in terms of display._
_Write your text after the "Text:" below._
* Text:

## Example of XML code
_Provide a sample encoding in XML of the new / changed element (with potential attributes)._
_In case of a conversion issue, the XML should ideally show the way an issue is dealt with now and the way you would like it to be dealt with in the future._
_Write your text after the "Example:" below._
* Example:
```
<timetable>
             <opening>Monday-Wednesday: 09.15-13.00, 14.00-16.45<lb/>
 Thursday-Friday: Closed</opening>
                    </timetable>
```

**Comment by janestevenson** [comment]
Have thought about `<lb>` used in other tags. Things like `<email> <webpage>` and `<telephone>` can use repeated tags.  Should `<closing>` have `<lb>`? Other more descriptive tags such as `<holdings>` allow for `<p>` tags.

**Comment by SJagodzinski** [comment]
I guess, we must not think about '<lb/>' in the control section (//control)?

As most EAG tag have no text subelements, like `<p>`, `<term>` or `<part>` it would be necessary to define each singe element for `<lb/>`. 

Allowing  `<lb/>` in `<p>` text elements it would solve the question for 15 elements:
- repository
- repositorhist
- building
- holdings
- computerPlaces
- researchServices
- internetAccess
- restorationlab
- reproductionser
- refreshment
- exhibition
- toursSessions
- otherServices
- resourceRelation
- eagRelation

Having  `<lb/>` in `<part>` is not necessary, I think. `<part>` is only used for names.

Further text elements with a possible requirement for longer texts are, in my opinion:
- directions
- rule
- _adminunit_ ???
- opening (as Jane requested)
- closing (to be align with opening)
- restaccess
- termsOfUse
- accessibility
- readersTicket
- advancedOrders

From a programmers perspektive, it might be useful to simply ad `<p>` as child of these 10 elements.

**Comment by janestevenson** [comment]
If we can add <p> to the above elements, and within <p> we can use <lb/> that works fine for me.

**Comment by kerstarno** [comment]
To be discussed during the WGoS meeting on 16 July. As an additional note to be kept in mind: EAG2012 does not include `<p>` as a separate formatting element, but uses `<descriptiveNote>` with `<p>` as a sub-element in most of the cases listed above.

**Comment by kerstarno** [comment]
Following various rounds of conversatins, WGoS has decided during their meeting on 25 September, that they will draft a summary of preferred options so far, which will then be shared with the community for feedback as part of the call for comments/suggestions on an upcoming major revision of EAG2012.

Summary and draft call will be discussed and reviewed during the WGoS meeting on 24 October.

**Comment by kerstarno** [comment]
During their meeting on 24 October, WGoS has agreed to create separate issues for the various aspects of the question discussed here in preparation for gathering user feedback and to - hopefully - make it easier for the community members to react on specific topics of their interest directly.

This issue here will hence be closed and will be replaced by the newly created ones for next steps.
